version: '3.7'

services:
  database:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: koroonabot
      POSTGRES_USER: koroonabot
      POSTGRES_PASSWORD: koroonabot
