spring:
  application:
    name: 'KoroonaBot'
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://localhost:5432/koroonabot
    username: koroonabot
    password: koroonabot
  jpa:
    database: postgresql
  flyway:
    locations: classpath:/db/migrations

logging:
  level:
    org:
      apache:
        http:
          wire: DEBUG

slack:
  installation:
    success-redirect-url: /installed
    error-redirect-url: /failed

covid:
  opendata:
    url: https://opendata.digilugu.ee/opendata_covid19_test_results.json
